[build]
  command = "npm run build"   # Specifies the build command
  publish = "out"             # Specifies the directory to publish (adjust if your output directory is different)

[[redirects]]                 # Optional: For URL redirects
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]                   # Optional: Custom HTTP headers
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"

